version: '3.5'

networks:
  docker-whmcs-network-internal:
    external: false
  docker-whmcs-network:
    external: true 

services:

  # Used for running WHMCS crontabs
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php-fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: ghcr.io/edythecow/whmcs-nginx:latest
    volumes:
      - ${DATA_DIR}/whmcs:/var/www/html
      - ${DATA_DIR}/whmcs_storage:/var/www/whmcs_storage
      - ${DATA_DIR}/nginx_logs:/var/log/nginx
    environment:
      - NGINX_DOMAIN=${DOMAIN}
      - TRAEFIK_SUBNET=${TRAEFIK_SUBNET}
      - PUBLIC_SERVER_IP=${PUBLIC_SERVER_IP}
    depends_on:
      - php-fpm
    networks:
      - docker-whmcs-network-internal
      - docker-whmcs-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker-whmcs-network"
      # HTTP
      - "traefik.http.routers.whmcs.entrypoints=web"
      - "traefik.http.routers.whmcs.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whmcs.middlewares=whmcs_https"
      - "traefik.http.middlewares.whmcs_https.redirectscheme.scheme=https"
      # HTTPS
      - "traefik.http.routers.whmcs-https.entrypoints=websecure"
      - "traefik.http.routers.whmcs-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whmcs-https.tls=true"
      - "traefik.http.routers.whmcs-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.whmcs-https.loadbalancer.server.port=80"
      # Basic auth for /admin page
      - "traefik.http.routers.whmcs-admin.rule=Host(`${DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.middlewares.basic-auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.routers.whmcs-admin.middlewares=basic-auth"
      - "traefik.http.routers.whmcs-admin.tls=true"

  php-fpm:
    image: ghcr.io/edythecow/whmcs-php-fpm:latest
    volumes:
      - ${DATA_DIR}/whmcs:/var/www/html
      - ${DATA_DIR}/whmcs_storage:/var/www/whmcs_storage
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=xwhmcs
    networks:
      - docker-whmcs-network-internal
    labels:
      - "ofelia.enabled=true"
      - "ofelia.job-exec.whmcs.schedule=@every 5m"
      - "ofelia.job-exec.whmcs.command=php -q /var/www/whmcs_storage/crons/cron.php"
     # Cronjobs for mail-to-ticket import. Uncomment to fetch new emails every minute.
     # - "ofelia.job-exec.whmcs-mail-import.schedule=@every 1m"
     # - "ofelia.job-exec.whmcs-mail-import.command=php -q /var/www/whmcs_storage/crons/pop.php"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    networks:
      - docker-whmcs-network-internal