services:

  nginx:
    image: ghcr.io/edythecow/whmcs-nginx:latest
    volumes:
      - whmcs-web-root:/var/www/html
      - whmcs-storage:/var/www/whmcs_storage
    environment:
      - NGINX_DOMAIN=${DOMAIN}
      - TRAEFIK_SUBNET=${TRAEFIK_SUBNET}
      - PUBLIC_SERVER_IP=${PUBLIC_SERVER_IP}
    depends_on:
      - php-fpm
    labels:
      # Basic auth for /admin page
      - "traefik.http.routers.whmcs-admin.rule=Host(`${DOMAIN}`) && (Path(`/admin`) || PathPrefix(`/admin/`))"
      - "traefik.http.routers.whmcs-admin.entrypoints=websecure"
      - "traefik.http.routers.whmcs-admin.tls=true"
      - "traefik.http.routers.whmcs-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.whmcs-admin.priority=10000"
      - "traefik.http.routers.whmcs-admin.service=whmcs-admin-svc"
      - "traefik.http.services.whmcs-admin-svc.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whmcs-admin-auth.basicauth.users=${BASIC_AUTH_CREDENTIALS}"
      - "traefik.http.routers.whmcs-admin.middlewares=whmcs-admin-auth@docker"

  php-fpm:
    image: ghcr.io/edythecow/whmcs-php-fpm:latest
    volumes:
      - whmcs-web-root:/var/www/html
      - whmcs-storage:/var/www/whmcs_storage
    environment:
      - PHP_IDE_CONFIG=xwhmcs
    labels:
      - "ofelia.enabled=true"
      - "ofelia.job-exec.whmcs.schedule=@every 5m"
      - "ofelia.job-exec.whmcs.command=php -q /var/www/whmcs_storage/crons/cron.php"
     # Cronjobs for mail-to-ticket import. Uncomment to fetch new emails every minute.
     # - "ofelia.job-exec.whmcs-mail-import.schedule=@every 1m"
     # - "ofelia.job-exec.whmcs-mail-import.command=php -q /var/www/whmcs_storage/crons/pop.php"

  # Used for running WHMCS crontabs
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php-fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - whmcs-database:/var/lib/mysql

volumes:
  whmcs-web-root:
  whmcs-storage:
  whmcs-database: