services:

  traefik:
    image: traefik:v3
    env_file:
      - .env
    networks:
      - docker-whmcs-network
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${DATA_DIR}/traefik/acme.json:/acme.json

networks:
  docker-whmcs-network:
    external: true