name: Build & Push Docker Image (Reusable)

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      cache_scope:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ inputs.image_tag }}
          cache-from: type=gha,scope=${{ inputs.cache_scope }}
          cache-to:   type=gha,mode=max,scope=${{ inputs.cache_scope }}