name: Build and publish WHMCS Docker images

on:
  push:
    branches: [ docker-images ]
    paths:
      - 'whmcs-php-fpm/**'
      - 'whmcs-nginx/**'
  pull_request:
    paths:
      - 'whmcs-php-fpm/**'
      - 'whmcs-nginx/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # required to push to ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push whmcs-php-fpm
        uses: docker/build-push-action@v6
        with:
          context: whmcs-php-fpm/
          push: true
          tags: ghcr.io/edythecow/whmcs-php-fpm:latest

      - name: Build & push whmcs-nginx
        uses: docker/build-push-action@v6
        with:
          context: whmcs-nginx/
          push: true
          tags: ghcr.io/edythecow/whmcs-nginx:latest
